/**
 * Deep-link builders for external real estate portals (Portal Inmobiliario, TocToc).
 * Pure functions — no side effects, no network calls.
 *
 * Verified URL schemes:
 *
 *   Portal Inmobiliario:
 *     /{operacion}/{tipo}/{comuna-slug}-{region-slug}   (real comuna)
 *     /{operacion}/{tipo}                               (otra_* or unknown)
 *     confirmed: /venta/departamento/las-condes-metropolitana
 *
 *   TocToc:
 *     /{operacion}/{tipo}/{comuna-slug}                 (real comuna, Región Metropolitana)
 *     /{operacion}/{tipo}/{region-slug}/{comuna-slug}   (real comuna, any other region)
 *     /{operacion}/{tipo}/{region-slug}                 (otra_*)
 *     /{operacion}/{tipo}                               (unknown)
 *     confirmed: /venta/departamento/providencia, /venta/departamento/biobio/concepcion, /venta/casa/biobio
 *
 * Slugs are generated by a best-effort algorithm (strip accents, lowercase,
 * hyphenate) — not individually verified against every comuna/region on the
 * live sites. Wrong slugs for unverified regions are a known, accepted risk.
 */

import { cityData } from "@/lib/comunaData";

export type Operacion = "venta" | "arriendo";
export type TipoPropiedad = "departamento" | "casa";

export interface PortalLinkParams {
  tipo: TipoPropiedad;
  cityId?: string;
  comunaId?: string;
  operacion?: Operacion;
}

const PORTAL_INMOBILIARIO_BASE = "https://www.portalinmobiliario.com";
const TOCTOC_BASE = "https://www.toctoc.com";

/** Shared slug algorithm: lowercase, strip accents, non-[a-z0-9] runs -> "-", trim. */
function slugify(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function isGenericComuna(comunaId?: string): boolean {
  return !comunaId || comunaId.startsWith("otra_");
}

export function buildPortalInmobiliarioUrl({
  tipo,
  cityId,
  comunaId,
  operacion = "venta",
}: PortalLinkParams): string {
  const base = `${PORTAL_INMOBILIARIO_BASE}/${operacion}/${tipo}`;
  if (isGenericComuna(comunaId)) return base;

  const city = cityId ? cityData[cityId] : undefined;
  const comuna = city?.comunas[comunaId!];
  if (!city || !comuna) return base;

  return `${base}/${slugify(comuna.label)}-${slugify(city.region)}`;
}

export function buildTocTocUrl({
  tipo,
  cityId,
  comunaId,
  operacion = "venta",
}: PortalLinkParams): string {
  const base = `${TOCTOC_BASE}/${operacion}/${tipo}`;
  const city = cityId ? cityData[cityId] : undefined;
  if (!city) return base;

  const regionSlug = slugify(city.region);
  const isMetropolitana = regionSlug === "metropolitana";

  if (isGenericComuna(comunaId)) return `${base}/${regionSlug}`;

  const comuna = city.comunas[comunaId!];
  if (!comuna) return `${base}/${regionSlug}`;

  const comunaSlug = slugify(comuna.label);
  return isMetropolitana ? `${base}/${comunaSlug}` : `${base}/${regionSlug}/${comunaSlug}`;
}
